### ISSUE TITLE
[FEAT][FE] добавить страницу авторизации

### ISSUE THREAD

**Issue by ignavan39** [unnamed-crm/web-client#3]
## Tasks:
- [x] авторизация / регистрация 
- [ ] мб подумать над тем не нужен ли нам рефреш токен, или время протухания токена с Бека, просто как фронт будет иначе понимать что токен протух 
- [ ] флоу авторизации посмотреть на бекенде 
- [ ] авторизация закрытая
- [ ] пользователь переходит по ссылке с почты 
- [ ] фронт sign-up имеет поля с временным паролем sign-in нет 
- [ ] форма ввода старого и нового пароля
